### ISSUE TITLE
Suggestions in Module 2

### ISSUE THREAD

**Issue by jae-cuz** [privacy-scaling-explorations/zk-contribution-program#5]
### Summary

A few suggestions to guide crypto-newcomers easily understand materials!

### Location

- Module Name: Module 2
- Section/Step: _(mentioned with Italic)_

### Proposed Correction

1. _Public-Key Cryptography and Key Exchange Protocols_ : With RSA Public Key encryption mentioned above, it would be helpful to mention that DLP is another hard problem that constructs DH key exchange and ElGamal Encryption. Also, I suggest to change the section name to "DLP based Public Key Cryptography".

2. _Hash Functions_ & _Merkle Trees_ : How about _Hash Function_ section including _Merkle Trees_ section? I suppose Merkle Tree is a usecase of hash function.

3. _Cryptographic Commitments_ : As _Pederson commitment_ is a way more understandable than _Polynomial Commitment_, I suppose we should introduce the former first. Moreover, Polynomial Commitment contains concept of bilinear maps , so that it is introduced again in _KZG Polynomial Commitments_ section in Module 3. Dropping this hard part in Module 2 would be another solution :)

4. _Digital Signatures_ : I mentioned in #4, suggesting to introduce DLP-Schnorr in Module 2. Also, describing the difference of commitment and signature would be helpful, too.

Sorry if you feel inconvinient reading my suggestions, but please kindly read comparing with the original article on the other side. ([link](https://pse-team.notion.site/Module-2-Crypto-Primitives-Encryption-Hash-Functions-and-Beyond-9b617504208b47b7aec84ef1d52f22aa))

**Comment by adrianmcli** [comment]
1. I think this makes sense. "DLP-based Public Key Cryptography" as a title is clear and specific. However, we need to make sure we immediately explain what DLP is underneath the heading.

2. I am not so sure about this one since Merkle Trees are a data-structure that just happens to use a lot of hash functions. I think it makes sense for Hash Functions to lead into Merkle Trees, but it might be confusing if we put it into the same section (people might think that merkle tree is a hash function 😅).

3. Actually, you bring up a lot of good points that I struggled with when writing the curriculum. I agree it makes sense to put polynomial commitments into the next module. I am just worried that Module 3 would be EVEN HARDER than it already is haha. But I do agree that it makes more sense logically.

4. Agreed.

**Comment by jae-cuz** [comment]
2 : Didn't think of that way! Thanks for pointing it out, really makes sense.
